// Fuente: docs/opciones_luna_de_miel.md (investigación del 2 de octubre de 2026).
// Fotos: Wikimedia Commons, ver src/photos.js para autor y licencia de cada una.
import { photos } from './photos'

const p = (...keys) => keys.map(k => photos[k])

const KAYAK = {
  PVR: 'https://www.kayak.com.mx/vuelos/Ciudad-de-Mexico-Juarez-y-otros-aeropuertos-MEX/Pto-Vallarta-Aeropuerto-Internacional-de-Puerto-Vallarta-PVR',
  HUX: 'https://www.kayak.com.mx/vuelos/Ciudad-de-Mexico-Juarez-y-otros-aeropuertos-MEX/Santa-Maria-Huatulco-HUX',
  ZIH: 'https://www.kayak.com.mx/vuelos/Ciudad-de-Mexico-Juarez-y-otros-aeropuertos-MEX/Ixtapa-Aeropuerto-Internacional-de-Ixtapa-Zihuatanejo-ZIH',
  SJD: 'https://www.kayak.com.mx/vuelos/Ciudad-de-Mexico-Juarez-y-otros-aeropuertos-MEX/San-Jose-del-Cabo-Los-Cabos-SJD',
  MZT: 'https://www.kayak.com.mx/vuelos/Ciudad-de-Mexico-Juarez-y-otros-aeropuertos-MEX/Mazatlan-Gen-Rafael-Buelna-MZT',
  CUN: 'https://www.kayak.com.mx/vuelos/Ciudad-de-Mexico-Juarez-y-otros-aeropuertos-MEX/Cancun-CUN',
  LAX: 'https://www.es.kayak.com/vuelos/Ciudad-de-Mexico-Juarez-y-otros-aeropuertos-MEX/Los-Angeles-LAX',
  HOU: 'https://www.kayak.com.mx/vuelos/Ciudad-de-Mexico-Benito-Juarez-MEX/Houston-HO1',
  TPA: 'https://www.kayak.com.mx/vuelos/Ciudad-de-Mexico-Juarez-y-otros-aeropuertos-MEX/Tampa-TPA',
}

const VISA = { label: 'Citas de visa B1/B2 (Embajada de EE. UU.)', url: 'https://mx.usembassy.gov/es/visas-es/', kind: 'info' }
const GOOGLE_FLIGHTS = { label: 'Google Flights (seguir precios)', url: 'https://www.google.com/travel/flights', kind: 'vuelo' }

// Estancia de hotel: 4 noches = 3 al 7 de mayo · 5 noches = 3 al 8 de mayo de 2027.
const hotelDays = (arrival, middle, last) => [
  { day: 'Lun 3 may', title: 'Vuelo desde CDMX y llegada', detail: arrival },
  ...middle.map((m, i) => ({ day: ['Mar 4 may', 'Mié 5 may', 'Jue 6 may', 'Vie 7 may'][i], ...m })),
  { day: 'Sáb 8 may', title: 'Regreso a CDMX', detail: last },
]

export const trips = [
  {
    id: 'secrets-huatulco',
    name: 'Secrets Huatulco Resort & Spa',
    type: 'Solo adultos',
    location: 'Huatulco, Oaxaca',
    price: '$45,500 MXN',
    priceAlt: '4 noches: $39,500 MXN',
    duration: '5 noches · 3 al 8 de mayo',
    images: p('huatulco1', 'huatulco2', 'huatulco3', 'huatulco4', 'huatulco5', 'huatulco6'),
    isRecommended: true,
    description: 'Bahías tranquilas, resort solo para adultos con 8 restaurantes sin reservación y mar del Pacífico sin sargazo.',
    summary: 'Es la opción que más se siente como luna de miel: bahías tranquilas, todas las suites con vista al mar y un ambiente íntimo, lejos del turismo masivo. El Pacífico en mayo es temporada seca y sin sargazo.',
    cons: 'Mayo es el mes más caro para volar a Huatulco. Si los boletos pasan de $16,000 para los dos, conviene bajar a 4 noches o cambiar a Dreams o Las Brisas.',
    costs: [
      ['Vuelo redondo para 2 (rango $10,000–18,000)', '~$14,000'],
      ['5 noches todo incluido (~$5,500 por noche)', '~$27,500'],
      ['Traslados aeropuerto ↔ hotel', '~$1,500'],
      ['Propinas e imprevistos', '~$2,500'],
    ],
    itinerary: hotelDays(
      'Vuelo MEX → HUX (Volaris, Viva o Aeroméxico). El aeropuerto está a ~20 min de Tangolunda. Check-in y cena de bienvenida (avisen que es luna de miel).',
      [
        { title: 'Día de resort', detail: 'Alberca, spa y playa privada de Tangolunda.' },
        { title: 'Tour de las bahías', detail: 'Paseo en lancha por las bahías (Órgano, Maguey, Cacaluta, San Agustín) con parada para snorkel.' },
        { title: 'Aventura o cultura', detail: 'Cascadas Mágicas de Copalita o el Parque Eco-Arqueológico Copalita; tarde libre.' },
        { title: 'Día libre', detail: 'Cena romántica en La Crucecita o en uno de los restaurantes del resort.' },
      ],
      'Check-out y vuelo HUX → MEX.',
    ),
    activities: [
      'Tour en lancha por las 9 bahías de Huatulco',
      'Snorkel en La Entrega y Bahía San Agustín',
      'Parque Eco-Arqueológico Copalita',
      'Parque ecoturístico Hagia Sofía y fincas de café en Pluma Hidalgo',
      'Liberación de tortugas (según temporada)',
      'Spa y cena romántica frente al mar',
    ],
    links: [
      { label: 'Secrets Huatulco (Kayak)', url: 'https://www.kayak.com/Tangolunda-Hotels-Secrets-Huatulco-Resort-Spa-Adults-Only.397593.ksp', kind: 'hotel' },
      { label: 'Vuelos MEX → HUX (Kayak)', url: KAYAK.HUX, kind: 'vuelo' },
      { label: 'Volaris CDMX → Huatulco', url: 'https://www.volaris.com/es-mx/vuelos-desde-mexico-df-a-huatulco', kind: 'vuelo' },
      { label: 'Paquetes a Huatulco (Kayak)', url: 'https://www.kayak.com.mx/packagetours/santa-maria-huatulco', kind: 'paquete' },
    ],
    alternatives: [
      { name: 'Las Brisas Huatulco', type: 'Todas las edades, vista al mar', night: '~$4,700', total: '$36,300 / $41,500', url: 'https://www.kayak.com/Santa-Maria-Huatulco-Hotels-Las-Brisas-Huatulco.40574.ksp' },
      { name: 'Dreams Huatulco', type: 'Todas las edades, bahía de Tangolunda', night: '~$5,000', total: '$37,500 / $43,000', url: 'https://www.kayak.com/Santa-Maria-Huatulco-Hotels-Dreams-Huatulco-Resort-Spa.25688.ksp' },
      { name: 'Barceló Huatulco', type: 'Todas las edades', night: 'Cotizar', total: '–', url: 'https://www.barcelo.com/es-mx/barcelo-huatulco/' },
    ],
  },
  {
    id: 'riu-palace-pacifico',
    name: 'Riu Palace Pacifico',
    type: 'Solo adultos',
    location: 'Nuevo Vallarta, Nayarit',
    price: '$38,000 MXN',
    priceAlt: '4 noches: $32,500 MXN',
    duration: '5 noches · 3 al 8 de mayo',
    images: p('vallarta1', 'vallarta2', 'vallarta3', 'vallarta4', 'vallarta5', 'vallarta6'),
    isRecommended: true,
    description: 'La de mejor relación calidad-precio. Vuelos baratos, te sobra presupuesto para un tour a las Islas Marietas.',
    summary: 'La mejor relación calidad-precio: vuelos baratos y frecuentes (Viva Aerobus también vuela desde el AIFA), resort solo para adultos y sobran más de $10,000 para tours como Islas Marietas o una cena en el centro de Vallarta.',
    cons: 'Zona más concurrida y menos "escondida" que Huatulco.',
    costs: [
      ['Vuelo redondo para 2', '~$9,000'],
      ['5 noches todo incluido (~$5,000 por noche)', '~$25,000'],
      ['Traslados aeropuerto ↔ hotel', '~$1,500'],
      ['Propinas e imprevistos', '~$2,500'],
    ],
    itinerary: hotelDays(
      'Vuelo MEX o AIFA → PVR (Viva, Volaris o Aeroméxico). Nuevo Vallarta está a ~20 min del aeropuerto. Check-in y atardecer en la playa.',
      [
        { title: 'Islas Marietas', detail: 'Tour en barco desde Nuevo Vallarta o La Cruz: Playa del Amor (escondida), snorkel y avistamiento de aves.' },
        { title: 'Día de resort', detail: 'Alberca, spa y playa; los restaurantes temáticos del Riu Palace.' },
        { title: 'Puerto Vallarta', detail: 'Malecón, esculturas, zona romántica y cena en el centro.' },
        { title: 'Sayulita o Punta Mita', detail: 'Pueblo mágico de surf, o día tranquilo en el hotel.' },
      ],
      'Check-out y vuelo PVR → CDMX.',
    ),
    activities: [
      'Islas Marietas y la Playa del Amor (cupo limitado, reservar con tiempo)',
      'Malecón de Puerto Vallarta y su zona romántica',
      'Pueblo mágico de Sayulita',
      'Yelapa en lancha (cascada y playa)',
      'Cena con vista en el Cerro de la Cruz o Conchas Chinas',
      'Avistamiento de ballenas: solo dic–mar (en mayo no hay)',
    ],
    links: [
      { label: 'Riu Palace Pacifico (oficial)', url: 'https://www.riu.com/es/hotel/mexico/vallarta-riviera-nayarit/hotel-riu-palace-pacifico/', kind: 'hotel' },
      { label: 'Vuelos MEX → PVR (Kayak)', url: KAYAK.PVR, kind: 'vuelo' },
      { label: 'Paquetes Viva desde CDMX', url: 'https://www.vivaaerobus.com/es-mx/paquetes/viajes-desde-ciudad-de-mexico-a-puerto-vallarta', kind: 'paquete' },
      { label: 'Paquetes Viva desde el AIFA', url: 'https://www.vivaaerobus.com/es-mx/paquetes/viajes-desde-felipe-angeles-cdmx-a-puerto-vallarta', kind: 'paquete' },
    ],
    alternatives: [
      { name: 'Riu Vallarta', type: 'Familiar', night: '~$4,500', total: '$30,500 / $35,500', url: 'https://www.riu.com/es/hotel/mexico/vallarta-riviera-nayarit/hotel-riu-vallarta/' },
      { name: 'Hyatt Ziva Puerto Vallarta', type: 'Todas las edades, playa propia', night: '~$7,500', total: '$42,500 / $50,500', url: 'https://www.kayak.com/Puerto-Vallarta-Hotels-Hyatt-Ziva-Puerto-Vallarta.2264594.ksp' },
    ],
  },
  {
    id: 'ovation-of-the-seas',
    name: 'Ovation of the Seas',
    type: 'Crucero',
    location: 'Los Ángeles → Catalina → Ensenada',
    price: '$48,135 MXN',
    priceAlt: 'Sin bebidas: $34,135 MXN',
    duration: '4 noches · 3 al 7 de mayo',
    images: p('ovation1', 'ovation2', 'ovation3', 'ovation4', 'catalina', 'ensenada'),
    isRecommended: true,
    description: 'Experiencia premium en altamar de Royal Caribbean. Total con paquete Deluxe de bebidas.',
    summary: 'Una experiencia distinta: barco de Royal Caribbean con la cápsula North Star, isla Catalina y Ensenada. El balcón ($541 USD por persona) cuesta casi lo mismo que la vista al mar ($543) y solo $154 USD más que el interior.',
    cons: 'Solo sirve si los dos ya tienen visa B1/B2. La única parada en México es Ensenada, y el paquete de bebidas (o el balcón) lo saca del presupuesto.',
    costs: [
      ['Crucero interior (2 × $387 USD) + propinas', '$16,135'],
      ['Vuelos MEX ↔ LAX para 2', '$13,000'],
      ['Traslados LAX ↔ puerto de San Pedro', '$2,000'],
      ['Hotel la noche del 2 de mayo', '$3,000'],
      ['Paquete Deluxe de bebidas (~$100 USD por persona por día)', '~$14,000'],
      ['Opcional: mejora a balcón (+$308 USD)', '+$5,390'],
    ],
    itinerary: [
      { day: 'Dom 2 may', title: 'Vuelo a Los Ángeles', detail: 'Volar un día antes y dormir cerca del puerto: un retraso el día 3 significa perder el barco.' },
      { day: 'Lun 3 may', title: 'Zarpe de Los Ángeles · 16:00', detail: 'Embarque al mediodía en el puerto de San Pedro.' },
      { day: 'Mar 4 may', title: 'Día en altamar', detail: 'North Star, simulador de surf FlowRider, paracaidismo iFly y shows.' },
      { day: 'Mié 5 may', title: 'Isla Catalina', detail: 'Avalon: caminar el pueblo, kayak o tirolesa.' },
      { day: 'Jue 6 may', title: 'Ensenada', detail: 'La Bufadora o cata de vino en el Valle de Guadalupe.' },
      { day: 'Vie 7 may', title: 'Llegada a Los Ángeles · 07:00', detail: 'Desembarque y vuelo de regreso a CDMX.' },
    ],
    activities: [
      'North Star: cápsula de cristal a 90 m sobre el mar',
      'FlowRider (surf) y RipCord by iFly (paracaidismo bajo techo)',
      'Avalon, isla Catalina: kayak, snorkel o tirolesa',
      'Ensenada: La Bufadora y vinos del Valle de Guadalupe',
      'Restaurantes de especialidad y shows en Two70',
    ],
    links: [
      { label: 'Tarifas e itinerario (iCruise)', url: 'https://m.icruise.com/itineraries/4-night-catalina-and-ensenada-getaway-cruise_ovation-of-the-seas_5-3-2027.html', kind: 'crucero' },
      { label: 'El barco (Royal Caribbean)', url: 'https://www.royalcaribbean.com/cruise-ships/ovation-of-the-seas', kind: 'crucero' },
      { label: 'Vuelos MEX → LAX (Kayak)', url: KAYAK.LAX, kind: 'vuelo' },
      VISA,
    ],
  },
  {
    id: 'carnival-radiance',
    name: 'Carnival Radiance',
    type: 'Crucero',
    location: 'Long Beach → Catalina → Ensenada',
    price: '$43,680 MXN',
    priceAlt: 'Sin bebidas: $32,125 MXN',
    duration: '4 noches · 3 al 7 de mayo',
    images: p('radiance1', 'radiance2', 'radiance3', 'radiance4', 'catalina', 'ensenada'),
    isRecommended: false,
    description: 'Incluye paquete CHEERS! de bebidas y propinas. Salida desde Long Beach (Los Ángeles).',
    summary: 'El crucero más barato de la lista. Tarifas por persona con impuestos: interior $327, vista al mar $427, balcón $547 y suite $932 USD.',
    cons: 'Requiere visa B1/B2. Barco más sencillo que el Ovation.',
    costs: [
      ['Crucero interior (2 × $327 USD) + propinas', '$13,825'],
      ['Vuelos MEX ↔ LAX para 2', '$13,000'],
      ['Traslados LAX ↔ puerto de Long Beach', '$2,300'],
      ['Hotel la noche del 2 de mayo', '$3,000'],
      ['Paquete CHEERS! (2 × 4 días × $82.54 USD)', '$11,555'],
    ],
    itinerary: [
      { day: 'Dom 2 may', title: 'Vuelo a Los Ángeles', detail: 'Dormir cerca de Long Beach para no arriesgar el zarpe.' },
      { day: 'Lun 3 may', title: 'Zarpe de Long Beach · 15:30', detail: 'El puerto está junto al Queen Mary.' },
      { day: 'Mar 4 may', title: 'Isla Catalina', detail: 'Avalon: pueblo, playa y paseos en barco con fondo de cristal.' },
      { day: 'Mié 5 may', title: 'Día en altamar', detail: 'Toboganes, minigolf, Guy\'s Burger Joint y comedia en vivo.' },
      { day: 'Jue 6 may', title: 'Ensenada', detail: 'La Bufadora, mercado de mariscos o Valle de Guadalupe.' },
      { day: 'Vie 7 may', title: 'Llegada a Long Beach · 08:00', detail: 'Desembarque y vuelo de regreso.' },
    ],
    activities: [
      'Parque acuático y toboganes a bordo',
      'Guy\'s Burger Joint y BlueIguana Cantina (incluidos)',
      'Avalon, isla Catalina',
      'Ensenada: La Bufadora y Valle de Guadalupe',
    ],
    links: [
      { label: 'Tarifas e itinerario (iCruise)', url: 'https://m.icruise.com/itineraries/4-night-baja-mexico-from-long-beach-(los-angeles)-cruise_carnival-radiance_5-3-2027.html', kind: 'crucero' },
      { label: 'El barco (Carnival)', url: 'https://www.carnival.com/cruise-ships/carnival-radiance', kind: 'crucero' },
      { label: 'Paquete CHEERS! (The Points Guy)', url: 'https://thepointsguy.com/cruise/carnival-cruise-cheers-drink-package/', kind: 'info' },
      { label: 'Vuelos MEX → LAX (Kayak)', url: KAYAK.LAX, kind: 'vuelo' },
      VISA,
    ],
  },
  {
    id: 'carnival-breeze',
    name: 'Carnival Breeze',
    type: 'Crucero',
    location: 'Galveston → Cozumel → Progreso',
    price: '$49,340 MXN',
    priceAlt: 'Sin bebidas: $34,895 MXN',
    duration: '5 noches · 3 al 8 de mayo',
    images: p('breeze1', 'breeze2', 'breeze3', 'breeze4', 'cozumel', 'progreso'),
    isRecommended: false,
    description: 'El crucero más "mexicano", con escalas en Cozumel y Progreso.',
    summary: 'Sale de Galveston (Houston) y hace dos escalas en México. Tarifas por persona con impuestos: interior $477, vista al mar $587, balcón $727 y suite $1,122 USD.',
    cons: 'Requiere visa B1/B2. Con bebidas queda al límite del presupuesto.',
    costs: [
      ['Crucero interior (2 × $477 USD) + propinas', '$19,670'],
      ['Vuelos MEX ↔ Houston para 2', '$10,000'],
      ['Shuttle aeropuerto de Houston ↔ Galveston', '$2,625'],
      ['Hotel la noche del 2 de mayo', '$2,600'],
      ['Paquete CHEERS! (2 × 5 días × $82.54 USD)', '$14,445'],
    ],
    itinerary: [
      { day: 'Dom 2 may', title: 'Vuelo a Houston', detail: 'Volaris, Viva, United o Aeroméxico. Dormir en Galveston.' },
      { day: 'Lun 3 may', title: 'Zarpe de Galveston · 15:30', detail: 'Embarque desde el mediodía.' },
      { day: 'Mar 4 may', title: 'Día en altamar', detail: 'WaterWorks, Serenity (zona solo adultos) y spa.' },
      { day: 'Mié 5 may', title: 'Cozumel · 09:00–17:00', detail: 'Snorkel en el arrecife Palancar o el parque Chankanaab.' },
      { day: 'Jue 6 may', title: 'Progreso, Yucatán · 09:00–17:00', detail: 'Mérida, cenotes o la zona arqueológica de Dzibilchaltún.' },
      { day: 'Vie 7 may', title: 'Día en altamar', detail: 'Cena elegante y último show.' },
      { day: 'Sáb 8 may', title: 'Llegada a Galveston · 08:00', detail: 'Shuttle a Houston y vuelo de regreso.' },
    ],
    activities: [
      'Snorkel en el arrecife Palancar (Cozumel)',
      'Parque Chankanaab o playa en Cozumel',
      'Mérida y cenotes desde Progreso',
      'Zona arqueológica de Dzibilchaltún',
      'Serenity: terraza solo para adultos a bordo',
    ],
    links: [
      { label: 'Tarifas e itinerario (iCruise)', url: 'https://m.icruise.com/itineraries/5-night-western-caribbean-from-galveston-cruise_carnival-breeze_5-3-2027.html', kind: 'crucero' },
      { label: 'El barco (Carnival)', url: 'https://www.carnival.com/cruise-ships/carnival-breeze', kind: 'crucero' },
      { label: 'Vuelos MEX → Houston (Kayak)', url: KAYAK.HOU, kind: 'vuelo' },
      { label: 'Cómo llegar de Houston a Galveston', url: 'https://www.cruzely.com/the-cheapest-way-to-get-from-houston-airports-to-the-galveston-port/', kind: 'info' },
      VISA,
    ],
  },
  {
    id: 'margaritaville-islander',
    name: 'Margaritaville at Sea Islander',
    type: 'Crucero',
    location: 'Tampa → Cozumel → Progreso',
    price: '$47,965 MXN',
    priceAlt: 'Sin bebidas: $37,465 MXN',
    duration: '5 noches · 3 al 8 de mayo',
    images: p('islander1', 'islander2', 'islander3', 'cozumel', 'progreso'),
    isRecommended: false,
    description: 'Experiencia relajada estilo Margaritaville. Incluye paquete de bebidas y propinas.',
    summary: 'Ambiente relajado de playa a bordo, con las mismas escalas mexicanas que el Breeze. Tarifas por persona desde $399 (interior) hasta $1,249 USD (suite).',
    cons: 'Requiere visa B1/B2. No hay vuelo directo de ida MEX → Tampa.',
    costs: [
      ['Crucero interior (2 × $399 USD) + propinas', '$17,465'],
      ['Vuelos MEX ↔ Tampa para 2 (con escala)', '$16,000'],
      ['Traslados TPA ↔ puerto', '$1,000'],
      ['Hotel la noche del 2 de mayo', '$3,000'],
      ['Paquete de bebidas (2 × 5 × $59.99 USD)', '$10,500'],
    ],
    itinerary: [
      { day: 'Dom 2 may', title: 'Vuelo a Tampa', detail: 'Con escala; dormir cerca del puerto.' },
      { day: 'Lun 3 may', title: 'Zarpe de Tampa · 15:30', detail: 'Embarque desde el mediodía.' },
      { day: 'Mar 4 may', title: 'Día en altamar', detail: 'Albercas, música en vivo y spa.' },
      { day: 'Mié 5 may', title: 'Cozumel · 08:00–16:00', detail: 'Snorkel, playa o tour por la isla.' },
      { day: 'Jue 6 may', title: 'Progreso, Yucatán · 08:00–16:00', detail: 'Mérida, cenotes o Dzibilchaltún.' },
      { day: 'Vie 7 may', title: 'Día en altamar', detail: 'Último día a bordo.' },
      { day: 'Sáb 8 may', title: 'Llegada a Tampa · 07:00', detail: 'Desembarque y vuelo de regreso.' },
    ],
    activities: [
      'Snorkel y playas de Cozumel',
      'Mérida y cenotes desde Progreso',
      'Música en vivo y ambiente "beach bar" a bordo',
    ],
    links: [
      { label: 'Itinerario (CruiseCompete)', url: 'https://www.cruisecompete.com/itins/islander_cruises_cabaagbb.html', kind: 'crucero' },
      { label: 'Naviera Margaritaville at Sea', url: 'https://www.margaritavilleatsea.com/', kind: 'crucero' },
      { label: 'Qué incluye (Eat Sleep Cruise)', url: 'https://eatsleepcruise.com/whats-included-on-margaritaville-at-sea/', kind: 'info' },
      { label: 'Vuelos MEX → Tampa (Kayak)', url: KAYAK.TPA, kind: 'vuelo' },
      VISA,
    ],
  },
  {
    id: 'krystal-ixtapa',
    name: 'Krystal Ixtapa',
    type: 'Todas las edades',
    location: 'Ixtapa-Zihuatanejo, Guerrero',
    price: '$30,500 MXN',
    priceAlt: '4 noches: $26,500 MXN',
    duration: '5 noches · 3 al 8 de mayo',
    images: p('ixtapa1', 'ixtapa2', 'ixtapa3', 'ixtapa4', 'ixtapa5', 'ixtapa6'),
    isRecommended: false,
    description: 'La opción más económica. Mar del Pacífico sin sargazo.',
    summary: 'La más barata de todas, con vuelos accesibles y un mar tranquilo. Ixtapa es moderna y Zihuatanejo, a 15 minutos, conserva su encanto de pueblo pesquero.',
    cons: 'Resort sencillo comparado con las opciones solo para adultos.',
    costs: [
      ['Vuelo redondo para 2', '~$9,000'],
      ['5 noches todo incluido (~$3,500 por noche)', '~$17,500'],
      ['Traslados aeropuerto ↔ hotel', '~$1,500'],
      ['Propinas e imprevistos', '~$2,500'],
    ],
    itinerary: hotelDays(
      'Vuelo MEX → ZIH. El aeropuerto está a ~20 min de la zona hotelera.',
      [
        { title: 'Isla Ixtapa', detail: 'Lancha desde Playa Linda, snorkel y comida de mariscos en la isla.' },
        { title: 'Día de resort', detail: 'Alberca y playa El Palmar.' },
        { title: 'Zihuatanejo', detail: 'Playa La Ropa, Playa Las Gatas y el centro del pueblo.' },
        { title: 'Ciclovía y atardecer', detail: 'Bicis por la ciclovía de Ixtapa y atardecer en El Faro.' },
      ],
      'Check-out y vuelo ZIH → MEX.',
    ),
    activities: [
      'Isla Ixtapa: snorkel en Playa Coral',
      'Playa La Ropa y Playa Las Gatas en Zihuatanejo',
      'Laguna de Barra de Potosí (aves y kayak)',
      'Ciclovía de Ixtapa y cocodrilario de Playa Linda',
    ],
    links: [
      { label: 'Krystal Ixtapa (oficial)', url: 'https://www.krystal-ixtapa.com/', kind: 'hotel' },
      { label: 'Vuelos MEX → ZIH (Kayak)', url: KAYAK.ZIH, kind: 'vuelo' },
      { label: 'Resorts todo incluido en Ixtapa (Kayak)', url: 'https://www.kayak.com/Ixtapa-Hotels_Resort.Tresort.19719.hotel.ksp', kind: 'hotel' },
    ],
    alternatives: [
      { name: 'Sunscape Dorado Pacífico', type: 'Bar en la alberca', night: '~$4,500', total: '$30,500 / $35,500', url: 'https://www.kayak.com/Ixtapa-Hotels-Sunscape-Dorado-Pacifico-Ixtapa-Resort-Spa.71184.ksp' },
      { name: 'Barceló Ixtapa', type: 'Todas las edades', night: '~$5,100', total: '$32,900 / $38,500', url: 'https://www.barcelo.com/es-mx/barcelo-ixtapa/' },
      { name: 'Club Med Ixtapa Pacific', type: 'Con actividades, cobra por persona', night: 'Cotizar', total: '–', url: 'https://www.clubmed.com.mx/r/ixtapa-pacific/y' },
    ],
  },
  {
    id: 'riu-santa-fe',
    name: 'Riu Santa Fe',
    type: 'Todas las edades',
    location: 'Los Cabos, BCS',
    price: '$39,500 MXN',
    priceAlt: '4 noches: $34,200 MXN',
    duration: '5 noches · 3 al 8 de mayo',
    images: p('cabos1', 'cabos2', 'cabos3', 'cabos4', 'cabos5', 'cabos6'),
    isRecommended: false,
    description: 'Ambiente de fiesta y vistas espectaculares al Arco de Cabo San Lucas.',
    summary: 'Paisajes desérticos frente al mar, el famoso Arco y una vida nocturna intensa. Ideal para alberca, paseos en barco y atardeceres.',
    cons: 'Mar bravo: en muchas playas no se puede nadar.',
    costs: [
      ['Vuelo redondo para 2', '~$11,000'],
      ['5 noches todo incluido (~$4,800 por noche)', '~$24,000'],
      ['Traslados aeropuerto ↔ hotel', '~$2,000'],
      ['Propinas e imprevistos', '~$2,500'],
    ],
    itinerary: hotelDays(
      'Vuelo MEX → SJD. El aeropuerto está a ~45 min de Cabo San Lucas.',
      [
        { title: 'El Arco', detail: 'Lancha con fondo de cristal al Arco, Playa del Amor y la lobera.' },
        { title: 'Día de resort', detail: 'Alberca y Playa El Médano.' },
        { title: 'San José del Cabo', detail: 'Centro histórico y galerías; snorkel en Playa Chileno o Santa María.' },
        { title: 'Atardecer en velero', detail: 'Crucero al atardecer por la bahía y cena en la marina.' },
      ],
      'Check-out y vuelo SJD → MEX.',
    ),
    activities: [
      'Lancha al Arco y Playa del Amor',
      'Snorkel en Bahía Chileno y Santa María',
      'Velero al atardecer',
      'San José del Cabo y su Art Walk (jueves)',
      'Pueblo mágico de Todos Santos',
    ],
    links: [
      { label: 'Riu Santa Fe (oficial)', url: 'https://www.riu.com/es/hotel/mexico/los-cabos/hotel-riu-santa-fe/', kind: 'hotel' },
      { label: 'Vuelos MEX → SJD (Kayak)', url: KAYAK.SJD, kind: 'vuelo' },
    ],
    alternatives: [
      { name: 'Grand Decameron Los Cabos', type: 'Económico', night: '~$3,200', total: '$27,800 / $31,500', url: 'https://www.decameron.com/es/hoteles/san-jose-del-cabo/decameron-los-cabos/' },
      { name: 'Riu Palace Cabo San Lucas', type: 'Más elegante', night: 'Cotizar', total: '–', url: 'https://www.riu.com/es/hotel/mexico/los-cabos/hotel-riu-palace-cabo-san-lucas/' },
    ],
  },
  {
    id: 'el-cid-marina',
    name: 'El Cid Marina Beach',
    type: 'Familiar',
    location: 'Mazatlán, Sinaloa',
    price: '$33,750 MXN',
    priceAlt: '4 noches: $28,900 MXN',
    duration: '5 noches · 3 al 8 de mayo',
    images: p('mazatlan1', 'mazatlan2', 'mazatlan3', 'mazatlan4', 'mazatlan5'),
    isRecommended: false,
    description: 'Buena relación calidad-precio y vuelos accesibles, también desde el AIFA.',
    summary: 'Destino con mucha vida local: malecón de 21 km, centro histórico, mariscos y atardeceres. El plan todo incluido es opcional (verificar al cotizar).',
    cons: 'El mar no es el más cristalino.',
    costs: [
      ['Vuelo redondo para 2', '~$8,000'],
      ['5 noches (~$4,350 por noche)', '~$21,750'],
      ['Traslados aeropuerto ↔ hotel', '~$1,500'],
      ['Propinas e imprevistos', '~$2,500'],
    ],
    itinerary: hotelDays(
      'Vuelo MEX o AIFA → MZT. Check-in en la Zona Dorada.',
      [
        { title: 'Centro histórico', detail: 'Plazuela Machado, Teatro Ángela Peralta y Olas Altas en pulmonía.' },
        { title: 'Isla de la Piedra', detail: 'Lancha corta a la isla, playa y pescado zarandeado.' },
        { title: 'El Faro', detail: 'Subida al Faro de Mazatlán al amanecer y día de playa.' },
        { title: 'Día libre', detail: 'Isla de Venados en kayak o spa.' },
      ],
      'Check-out y vuelo MZT → CDMX.',
    ),
    activities: [
      'Malecón y clavadistas de Olas Altas',
      'Centro histórico y Teatro Ángela Peralta',
      'Subida a El Faro (de los más altos del mundo)',
      'Isla de la Piedra e Isla de Venados',
    ],
    links: [
      { label: 'El Cid Marina Beach (oficial)', url: 'https://www.elcid.com/mazatlan/el-cid-marina-beach-hotel/', kind: 'hotel' },
      { label: 'Vuelos MEX → MZT (Kayak)', url: KAYAK.MZT, kind: 'vuelo' },
      { label: 'Vuelos AIFA → MZT (Kayak)', url: 'https://www.kayak.com.mx/vuelos/Ciudad-de-Mexico-Aeropuerto-Internacional-Lic-Adolfo-Lopez-Mateos-TLC/Mazatlan-Gen-Rafael-Buelna-MZT', kind: 'vuelo' },
    ],
    alternatives: [
      { name: 'Pueblo Bonito Emerald Bay', type: 'Todo incluido', night: '~$4,400', total: '$29,100 / $34,000', url: 'https://www.pueblobonito.com/resorts/emerald-bay' },
      { name: 'Riu Emerald Bay', type: 'Todo incluido', night: 'Cotizar', total: '–', url: 'https://www.riu.com/es/hotel/mexico/mazatlan/hotel-riu-emerald-bay/' },
    ],
  },
  {
    id: 'grand-oasis-cancun',
    name: 'Grand Oasis Cancún',
    type: 'Económico',
    location: 'Cancún, Quintana Roo',
    price: '$35,000 MXN',
    priceAlt: '4 noches: $30,500 MXN',
    duration: '5 noches · 3 al 8 de mayo',
    images: p('cancun1', 'cancun2', 'cancun3', 'cancun4', 'cancun5'),
    isRecommended: false,
    description: 'Resort grande y económico en el Caribe mexicano.',
    summary: 'El Caribe a buen precio, con muchísimas opciones de excursiones. Si eligen el Caribe, prefieran la zona hotelera norte (frente a Bahía de Mujeres), que suele estar menos afectada por el sargazo.',
    cons: '2026 fue el peor año de sargazo registrado en Quintana Roo, con el pico en mayo y junio. Revisar el semáforo una semana antes.',
    costs: [
      ['Vuelo redondo para 2 (mayo es caro)', '~$11,000'],
      ['5 noches todo incluido (~$4,000 por noche)', '~$19,500'],
      ['Traslados aeropuerto ↔ hotel', '~$2,000'],
      ['Propinas e imprevistos', '~$2,500'],
    ],
    itinerary: hotelDays(
      'Vuelo MEX → CUN y traslado a la zona hotelera (~20 min).',
      [
        { title: 'Isla Mujeres', detail: 'Ferry o catamarán, Playa Norte y carrito de golf por la isla.' },
        { title: 'Día de resort', detail: 'Alberca y playa (si el sargazo lo permite).' },
        { title: 'Cenotes', detail: 'Ruta de los cenotes en Puerto Morelos o Chichén Itzá (día completo).' },
        { title: 'Playa del Carmen', detail: 'Quinta Avenida o un parque como Xcaret.' },
      ],
      'Check-out y vuelo CUN → MEX.',
    ),
    activities: [
      'Isla Mujeres y Playa Norte',
      'Ruta de los Cenotes',
      'Chichén Itzá',
      'Xcaret, Xel-Há o Xplor',
      'Snorkel en el MUSA (museo subacuático)',
    ],
    links: [
      { label: 'Grand Oasis Cancún (oficial)', url: 'https://www.oasishoteles.com/es/hoteles/grand-oasis-cancun', kind: 'hotel' },
      { label: 'Grand Oasis Cancún (Kayak)', url: 'https://www.kayak.com.mx/Cancun-Hoteles-Grand-Oasis-Cancun.185783.ksp', kind: 'hotel' },
      { label: 'Vuelos MEX → CUN (Kayak)', url: KAYAK.CUN, kind: 'vuelo' },
      { label: 'Pronóstico de sargazo (Por Esto)', url: 'https://www.poresto.com/quintana-roo/2026/1/23/preven-fuerte-recale-de-sargazo-en-quintana-roo-durante-primavera-y-verano-de-2026.html', kind: 'info' },
    ],
    alternatives: [
      { name: 'Riu Caribe', type: 'Zona norte (menos sargazo)', night: '~$6,500', total: '$40,500 / $47,500', url: 'https://www.riu.com/es/hotel/mexico/cancun/hotel-riu-caribe/' },
      { name: 'Riu Palace Riviera Maya', type: 'Playa del Carmen', night: '~$6,000', total: '$39,000 / $45,500', url: 'https://www.riu.com/es/hotel/mexico/playa-del-carmen/hotel-riu-palace-riviera-maya/' },
      { name: 'Breathless Cancún Soul', type: 'Solo adultos', night: '~$7,000', total: '$42,500 / $50,000', url: 'https://www.kayak.com/Cancun-Hotels-Breathless-Cancun-Soul-Resort-And-Spa.7977537.ksp' },
      { name: 'Riu Palace Las Américas', type: 'Solo adultos', night: 'Cotizar', total: '–', url: 'https://www.riu.com/es/hotel/mexico/cancun/hotel-riu-palace-las-americas/' },
    ],
  },
]

export const generalLinks = [
  { label: 'Viva Aerobus Paquetes', url: 'https://www.vivaaerobus.com/es-mx/paquetes/viajes-a-puerto-vallarta', kind: 'paquete' },
  { label: 'PriceTravel Paquetes', url: 'https://www.pricetravel.com/es-mx/paquetes', kind: 'paquete' },
  { label: 'Kayak Paquetes', url: 'https://www.kayak.com.mx/packagetours/méxico', kind: 'paquete' },
  GOOGLE_FLIGHTS,
  VISA,
]
